version: "3.9"

services:
  frontend:
    container_name: frontend_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
